"""empty message

Revision ID: 385f874eb2d0
Revises: 66066cfa3a9c
Create Date: 2023-06-12 13:31:54.496266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385f874eb2d0'
down_revision = '66066cfa3a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conservation_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('native_habitat', sa.String(length=200), nullable=True))
        batch_op.alter_column('common_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('scientific_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.alter_column('scientific_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('common_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('native_habitat')
        batch_op.drop_column('conservation_status')

    # ### end Alembic commands ###
